/*
 * Calibration Constants for EMG-to-Force Prosthetic Hand
 * ======================================================
 *
 * This file is auto-generated by src/models/export_model.py
 * after training. It contains:
 *   1. MinMaxScaler parameters (from training normalization)
 *   2. Default calibration offsets
 *   3. Actuator tuning parameters
 *
 * To regenerate after retraining:
 *   python -m src.models.export_model --model outputs/models/best_model.pt
 */

#ifndef CALIBRATION_H
#define CALIBRATION_H

// ─── Input Normalization (MinMaxScaler from training) ────────────────
// These values are fitted on the training set and must match exactly.
// Updated by export_model.py after training.

// Per-channel minimum values (before scaling)
static const float INPUT_MIN[] = {0.0f, 0.0f};

// Per-channel scale factors: 1 / (max - min)
static const float INPUT_SCALE[] = {1.0f, 1.0f};

// Output (force) normalization
static const float FORCE_MIN = 0.0f;
static const float FORCE_SCALE = 1.0f;  // 1 / (force_max - force_min)

// ─── User Calibration Defaults ──────────────────────────────────────
// These are overridden at runtime via Bluetooth commands
// from the calibration mobile app.

#define DEFAULT_CAL_SCALE   1.0f
#define DEFAULT_CAL_OFFSET  0.0f
#define DEFAULT_FORCE_MAX   1.0f

// ─── Actuator Configuration ─────────────────────────────────────────
// PWM range for linear actuators
#define ACTUATOR_PWM_MIN    0       // Minimum PWM (fully open)
#define ACTUATOR_PWM_MAX    255     // Maximum PWM (fully closed)

// Per-finger gain factors (tune for mechanical differences)
// Values 0.0 - 1.0, multiply predicted force before PWM mapping
#define THUMB_GAIN    1.0f
#define INDEX_GAIN    1.0f
#define MIDDLE_GAIN   1.0f
#define RING_GAIN     0.9f    // Ring/little often need less force
#define LITTLE_GAIN   0.8f

// Dead zone: minimum force below which actuators don't move
// Prevents jitter from EMG noise
#define FORCE_DEAD_ZONE  0.05f

// ─── Safety Limits ──────────────────────────────────────────────────
// Maximum continuous PWM duty cycle (thermal protection)
#define MAX_CONTINUOUS_PWM  230

// Force rate limiter: max change per inference cycle
// Prevents sudden jerky movements (units: normalized force per step)
#define MAX_FORCE_RATE  0.15f

#endif  // CALIBRATION_H
