/*
 * EMG-to-Force Real-Time Inference for InMoov Prosthetic Hand
 * ============================================================
 *
 * Hardware Requirements:
 *   - Arduino Mega 2560 (or Due for better floating-point)
 *   - 2x EMG sensors (MyoWare 2.0 or equivalent)
 *   - 5x Linear actuators (for finger control)
 *   - HC-05/06 Bluetooth module (for calibration app)
 *
 * Wiring:
 *   A0 : EMG Channel 1 (MRMR-selected)
 *   A1 : EMG Channel 2 (MRMR-selected)
 *   D3 : Thumb actuator (PWM)
 *   D5 : Index actuator (PWM)
 *   D6 : Middle actuator (PWM)
 *   D9 : Ring actuator (PWM)
 *   D10: Little actuator (PWM)
 *   TX1/RX1: Bluetooth module (Serial1)
 *
 * Model: GRU(2->50, relu) -> Dense(100, relu) -> Dense(1)
 * Inference rate: ~80 Hz (matching RMS envelope rate)
 *
 * Author: [Your Name]
 * Date: 2026
 */

#include "model_weights.h"  // Generated by src/models/export_model.py

// ─── Pin Configuration ───────────────────────────────────────────
#define EMG_CH1_PIN    A0
#define EMG_CH2_PIN    A1

#define THUMB_PIN      3
#define INDEX_PIN      5
#define MIDDLE_PIN     6
#define RING_PIN       9
#define LITTLE_PIN     10

// ─── Timing ──────────────────────────────────────────────────────
#define SAMPLE_RATE_HZ    2000   // Raw EMG sampling rate
#define ENVELOPE_RATE_HZ  80     // RMS envelope rate (25ms windows)
#define RMS_WINDOW_SIZE   25     // Samples per RMS window (2000/80)

// ─── Model Constants (must match model_weights.h) ────────────────
// INPUT_SIZE, HIDDEN_SIZE, DENSE_SIZE, OUTPUT_SIZE, SEQ_LEN
// are defined in model_weights.h

// ─── Calibration ─────────────────────────────────────────────────
float cal_scale = 1.0;       // Updated via Bluetooth calibration app
float cal_offset = 0.0;
float force_max = 1.0;       // Maximum force for PWM mapping

// ─── Buffers ─────────────────────────────────────────────────────
float emg_raw_buffer[RMS_WINDOW_SIZE][INPUT_SIZE];  // Raw EMG samples
int raw_idx = 0;

float seq_buffer[SEQ_LEN][INPUT_SIZE];  // RMS envelope sequence
int seq_idx = 0;
bool seq_ready = false;

float hidden_state[HIDDEN_SIZE];  // GRU hidden state

// ─── MinMax Scaler Parameters ────────────────────────────────────
// These should be exported alongside model weights
// For now, using identity scaling (update after training)
float input_min[SEQ_LEN * INPUT_SIZE];
float input_scale[SEQ_LEN * INPUT_SIZE];
float force_min_val = 0.0;
float force_scale_val = 1.0;

// ─── Forward Declarations ────────────────────────────────────────
float compute_rms(int channel);
void gru_forward(float* input_seq, float* hidden, float* output);
void dense_forward(float* input, float* output, const float* weights,
                   const float* bias, int in_size, int out_size, bool relu);
void apply_relu(float* arr, int size);
void drive_actuators(float force);
void handle_bluetooth();

// ═══════════════════════════════════════════════════════════════════
void setup() {
    Serial.begin(115200);
    Serial1.begin(9600);  // Bluetooth

    // Initialize actuator pins
    pinMode(THUMB_PIN, OUTPUT);
    pinMode(INDEX_PIN, OUTPUT);
    pinMode(MIDDLE_PIN, OUTPUT);
    pinMode(RING_PIN, OUTPUT);
    pinMode(LITTLE_PIN, OUTPUT);

    // Initialize buffers
    memset(emg_raw_buffer, 0, sizeof(emg_raw_buffer));
    memset(seq_buffer, 0, sizeof(seq_buffer));
    memset(hidden_state, 0, sizeof(hidden_state));

    Serial.println("EMG-to-Force Predictor Ready");
    Serial.println("Waiting for EMG signal...");
}

// ═══════════════════════════════════════════════════════════════════
void loop() {
    static unsigned long last_sample_us = 0;
    static unsigned long last_envelope_ms = 0;
    unsigned long now_us = micros();
    unsigned long now_ms = millis();

    // ─── Sample EMG at 2000 Hz ───────────────────────────────────
    if (now_us - last_sample_us >= 500) {  // 500us = 2000 Hz
        last_sample_us = now_us;

        // Read raw EMG
        emg_raw_buffer[raw_idx][0] = analogRead(EMG_CH1_PIN) / 1023.0;
        emg_raw_buffer[raw_idx][1] = analogRead(EMG_CH2_PIN) / 1023.0;
        raw_idx++;

        // ─── Compute RMS envelope every 25ms ─────────────────────
        if (raw_idx >= RMS_WINDOW_SIZE) {
            raw_idx = 0;

            // Compute RMS for each channel
            float rms_vals[INPUT_SIZE];
            for (int ch = 0; ch < INPUT_SIZE; ch++) {
                float sum_sq = 0.0;
                for (int i = 0; i < RMS_WINDOW_SIZE; i++) {
                    float v = emg_raw_buffer[i][ch];
                    sum_sq += v * v;
                }
                rms_vals[ch] = sqrt(sum_sq / RMS_WINDOW_SIZE);
            }

            // Shift sequence buffer and add new values
            for (int t = 0; t < SEQ_LEN - 1; t++) {
                for (int ch = 0; ch < INPUT_SIZE; ch++) {
                    seq_buffer[t][ch] = seq_buffer[t + 1][ch];
                }
            }
            for (int ch = 0; ch < INPUT_SIZE; ch++) {
                seq_buffer[SEQ_LEN - 1][ch] = rms_vals[ch];
            }

            seq_idx++;
            if (seq_idx >= SEQ_LEN) {
                seq_ready = true;
            }

            // ─── Run GRU inference ───────────────────────────────
            if (seq_ready) {
                // Reset hidden state for each inference
                // (stateless per-sequence, matching training)
                memset(hidden_state, 0, sizeof(hidden_state));

                float output;
                gru_forward(&seq_buffer[0][0], hidden_state, &output);

                // Apply calibration
                float force = output * cal_scale + cal_offset;
                force = constrain(force, 0.0, force_max);

                // Drive actuators
                drive_actuators(force);

                // Send to Serial for monitoring
                Serial.print("Force: ");
                Serial.println(force, 4);
            }
        }
    }

    // ─── Handle Bluetooth calibration commands ───────────────────
    handle_bluetooth();
}

// ─── GRU Forward Pass ────────────────────────────────────────────
void gru_forward(float* input_seq, float* hidden, float* output) {
    /*
     * Process each timestep through the GRU, then apply:
     *   ReLU -> Dense(100, relu) -> Dense(1)
     *
     * GRU equations (per timestep):
     *   z = sigmoid(W_iz @ x + b_iz + W_hz @ h + b_hz)  // update gate
     *   r = sigmoid(W_ir @ x + b_ir + W_hr @ h + b_hr)  // reset gate
     *   n = tanh(W_in @ x + b_in + r*(W_hn @ h + b_hn)) // new gate
     *   h' = (1-z)*n + z*h
     *
     * PyTorch GRU weight layout (weight_ih, weight_hh, bias_ih, bias_hh):
     *   Each weight is stacked [W_r, W_z, W_n] (3*hidden_size rows)
     */

    // NOTE: Full GRU implementation requires significant code.
    // For production deployment, consider using TensorFlow Lite Micro
    // or ONNX Runtime for microcontrollers.
    //
    // This is a simplified placeholder showing the inference structure.
    // Replace with actual weight-based computation or use a library.

    // For now: simplified pass-through (replace with actual GRU math)
    // The actual implementation should use the weights from model_weights.h

    // ... GRU timestep loop would go here ...
    // After processing all timesteps:

    // Apply ReLU to final hidden state
    float h_relu[HIDDEN_SIZE];
    for (int i = 0; i < HIDDEN_SIZE; i++) {
        h_relu[i] = hidden[i] > 0 ? hidden[i] : 0;
    }

    // Dense layer 1: h_relu (50) -> dense1 (100) + ReLU
    float dense1[DENSE_SIZE];
    dense_forward(h_relu, dense1, fc1_weight, fc1_bias, HIDDEN_SIZE, DENSE_SIZE, true);

    // Dense layer 2: dense1 (100) -> output (1)
    dense_forward(dense1, output, fc_out_weight, fc_out_bias, DENSE_SIZE, OUTPUT_SIZE, false);
}

// ─── Dense Layer Forward Pass ────────────────────────────────────
void dense_forward(float* input, float* output, const float* weights,
                   const float* bias, int in_size, int out_size, bool relu) {
    for (int o = 0; o < out_size; o++) {
        float sum = bias[o];
        for (int i = 0; i < in_size; i++) {
            sum += weights[o * in_size + i] * input[i];
        }
        output[o] = relu ? max(0.0f, sum) : sum;
    }
}

// ─── Drive Actuators ─────────────────────────────────────────────
void drive_actuators(float force) {
    // Map normalized force [0, 1] to PWM [0, 255]
    int pwm = constrain((int)(force * 255.0), 0, 255);

    // All fingers driven proportionally to total grip force
    // In a more advanced version, each finger could have
    // independent force control
    analogWrite(THUMB_PIN, pwm);
    analogWrite(INDEX_PIN, pwm);
    analogWrite(MIDDLE_PIN, pwm);
    analogWrite(RING_PIN, pwm);
    analogWrite(LITTLE_PIN, pwm);
}

// ─── Bluetooth Calibration Handler ───────────────────────────────
void handle_bluetooth() {
    if (Serial1.available()) {
        String cmd = Serial1.readStringUntil('\n');
        cmd.trim();

        if (cmd.startsWith("CAL_SCALE:")) {
            cal_scale = cmd.substring(10).toFloat();
            Serial1.print("OK:SCALE=");
            Serial1.println(cal_scale);
        }
        else if (cmd.startsWith("CAL_OFFSET:")) {
            cal_offset = cmd.substring(11).toFloat();
            Serial1.print("OK:OFFSET=");
            Serial1.println(cal_offset);
        }
        else if (cmd.startsWith("FORCE_MAX:")) {
            force_max = cmd.substring(10).toFloat();
            Serial1.print("OK:FMAX=");
            Serial1.println(force_max);
        }
        else if (cmd == "STATUS") {
            Serial1.print("SCALE=");
            Serial1.print(cal_scale);
            Serial1.print(",OFFSET=");
            Serial1.print(cal_offset);
            Serial1.print(",FMAX=");
            Serial1.println(force_max);
        }
        else if (cmd == "RESET") {
            cal_scale = 1.0;
            cal_offset = 0.0;
            force_max = 1.0;
            Serial1.println("OK:RESET");
        }
    }
}
